services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - N8N_LOG_LEVEL=debug
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
      - ./dist:/home/node/.n8n/custom/dist
      - ./node_modules:/home/node/.n8n/node_modules
    restart: unless-stopped

volumes:
  n8n_data:
    driver: local
